# Generated by Django 3.2.2 on 2021-05-08 17:36

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Motivation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='request',
        ),
        migrations.AddField(
            model_name='post',
            name='cin',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='12345678', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
